version: '3'

services:
  db:
    image: mysql:8
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=testpass
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    networks:
      - api-network
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend
    environment:
      - ENV=test
      - PORT=8080
      - DB_DATABASE=test
      - DB_USER=test
      - DB_PASSWORD=test
      - DB_HOST=db
      - DB_PORT=3306
      - DB_ROOT_PASSWORD=testpass
    ports:
      - 8080:8080
    restart: always
    networks:
      - api-network
networks:
  api-network:
    driver: bridge
