name: CD

on:
  push:
    branches:
      - main

jobs:
  gcr-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: GCP Authenticate
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Configure docker
      run: gcloud auth configure-docker --quiet
    - name: Build
      run: docker build -t asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:$GITHUB_SHA -f ./docker/Dockerfile.prod.backend .
    - name: Push
      run: docker push asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:$GITHUB_SHA
  gh-pages-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14.16.0"] # lts
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2 # ref: https://github.com/actions/setup-node
        with: 
          node-version: ${{ matrix.node }}
      - name: Install redoc
        run: npm install -g redoc-cli
      - name: Build openAPI file
        run: redoc-cli bundle ./docs/swagger.yaml
      - name: Output file contents # GitHub Actionsのログを見てデバッグする時用
        run: cat ./redoc-static.html
      - name: Create public directory
        run: mkdir -p ./public
      - name: Move file
        run: mv ./redoc-static.html ./public/index.html
      - name: Deploy html
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - name: remove directory
        run: rm -rf ./public
