name: CD-test

on: push

jobs:
  gh-pages-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14.16.0"] # lts
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2 # ref: https://github.com/actions/setup-node
        with: 
          node-version: ${{ matrix.node }}
      - name: Install redoc
        run: npm install -g redoc-cli
      - name: Build openAPI file
        run: redoc-cli bundle ./docs/swagger.yaml
      - name: Output file contents # GitHub Actionsのログを見てデバッグする時用
        run: cat ./redoc-static.html
      - name: Create public directory
        run: mkdir -p ./public
      - name: Move file
        run: mv ./redoc-static.html ./public/index.html
      - name: Deploy html
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - name: remove directory
        run: rm -rf ./public
